import { useParams, useNavigate } from 'react-router-dom'
import { useQuery } from '@tanstack/react-query'
import { getReport } from '../api/reports.api'
import Card from '../components/ui/Card'
import Badge from '../components/ui/Badge'
import Skeleton from '../components/ui/Skeleton'
import Button from '../components/ui/Button'
import { formatDate } from '../utils/formatDate'

export default function ReportDetail() {
  const { id } = useParams()
  const navigate = useNavigate()

  const { data: report, isLoading } = useQuery({
    queryKey: ['report', id],
    queryFn: () => getReport(id).then((r) => r.data),
  })

  const handleCopy = () => {
    navigator.clipboard.writeText(report?.fullText || '')
  }

  const handlePrint = () => {
    window.print()
  }

  if (isLoading) {
    return (
      <div className='space-y-6'>
        <Skeleton height='h-8' width='w-64' />
        <Card>
          <div className='space-y-3'>
            {[...Array(6)].map((_, i) => (
              <Skeleton key={i} height='h-4' width={i % 2 === 0 ? 'w-full' : 'w-3/4'} />
            ))}
          </div>
        </Card>
      </div>
    )
  }

  return (
    <div className='space-y-6 max-w-3xl'>

      {/* Back button */}
      <button
        onClick={() => navigate('/reports')}
        className='flex items-center gap-2 text-sm text-gray-500 hover:text-gray-700 transition-colors'
      >
        <svg className='w-4 h-4' fill='none' viewBox='0 0 24 24' stroke='currentColor'>
          <path strokeLinecap='round' strokeLinejoin='round' strokeWidth={2} d='M15 19l-7-7 7-7' />
        </svg>
        Back to reports
      </button>

      {/* Report header */}
      <div className='flex items-start justify-between'>
        <div>
          <h2 className='text-xl font-semibold text-gray-900'>
            Week of {formatDate(report?.weekStart)}
          </h2>
          <div className='flex items-center gap-2 mt-2'>
            <Badge variant={report?.growth >= 0 ? 'green' : 'red'}>
              {report?.growth >= 0 ? '+' : ''}{report?.growth}% growth
            </Badge>
            <span className='text-xs text-gray-400'>Generated by AI</span>
          </div>
        </div>
        <div className='flex gap-2'>
          <Button variant='secondary' size='sm' onClick={handleCopy}>
            <svg className='w-4 h-4 mr-1.5' fill='none' viewBox='0 0 24 24' stroke='currentColor'>
              <path strokeLinecap='round' strokeLinejoin='round' strokeWidth={2} d='M8 16H6a2 2 0 01-2-2V6a2 2 0 012-2h8a2 2 0 012 2v2m-6 12h8a2 2 0 002-2v-8a2 2 0 00-2-2h-8a2 2 0 00-2 2v8a2 2 0 002 2z' />
            </svg>
            Copy
          </Button>
          <Button variant='secondary' size='sm' onClick={handlePrint}>
            <svg className='w-4 h-4 mr-1.5' fill='none' viewBox='0 0 24 24' stroke='currentColor'>
              <path strokeLinecap='round' strokeLinejoin='round' strokeWidth={2} d='M17 17h2a2 2 0 002-2v-4a2 2 0 00-2-2H5a2 2 0 00-2 2v4a2 2 0 002 2h2m2 4h6a2 2 0 002-2v-4a2 2 0 00-2-2H9a2 2 0 00-2 2v4a2 2 0 002 2zm8-12V5a2 2 0 00-2-2H9a2 2 0 00-2 2v4h10z' />
            </svg>
            Print
          </Button>
        </div>
      </div>

      {/* Summary */}
      <Card>
        <div className='flex items-center gap-2 mb-3'>
          <div className='w-7 h-7 bg-indigo-50 rounded-lg flex items-center justify-center'>
            <svg className='w-4 h-4 text-indigo-600' fill='none' viewBox='0 0 24 24' stroke='currentColor'>
              <path strokeLinecap='round' strokeLinejoin='round' strokeWidth={2} d='M13 16h-1v-4h-1m1-4h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z' />
            </svg>
          </div>
          <h3 className='text-sm font-semibold text-gray-900'>Summary</h3>
        </div>
        <p className='text-sm text-gray-700 leading-relaxed'>{report?.summary}</p>
      </Card>

      {/* Highlights */}
      <Card>
        <div className='flex items-center gap-2 mb-3'>
          <div className='w-7 h-7 bg-green-50 rounded-lg flex items-center justify-center'>
            <svg className='w-4 h-4 text-green-600' fill='none' viewBox='0 0 24 24' stroke='currentColor'>
              <path strokeLinecap='round' strokeLinejoin='round' strokeWidth={2} d='M5 13l4 4L19 7' />
            </svg>
          </div>
          <h3 className='text-sm font-semibold text-gray-900'>Highlights</h3>
        </div>
        <ul className='space-y-2'>
          {report?.highlights?.map((item, i) => (
            <li key={i} className='flex items-start gap-2 text-sm text-gray-700'>
              <span className='w-1.5 h-1.5 rounded-full bg-green-500 mt-2 flex-shrink-0' />
              {item}
            </li>
          ))}
        </ul>
      </Card>

      {/* Warnings */}
      {report?.warnings?.length > 0 && (
        <Card>
          <div className='flex items-center gap-2 mb-3'>
            <div className='w-7 h-7 bg-yellow-50 rounded-lg flex items-center justify-center'>
              <svg className='w-4 h-4 text-yellow-600' fill='none' viewBox='0 0 24 24' stroke='currentColor'>
                <path strokeLinecap='round' strokeLinejoin='round' strokeWidth={2} d='M12 9v2m0 4h.01m-6.938 4h13.856c1.54 0 2.502-1.667 1.732-3L13.732 4c-.77-1.333-2.694-1.333-3.464 0L3.34 16c-.77 1.333.192 3 1.732 3z' />
              </svg>
            </div>
            <h3 className='text-sm font-semibold text-gray-900'>Watch Out</h3>
          </div>
          <ul className='space-y-2'>
            {report?.warnings?.map((item, i) => (
              <li key={i} className='flex items-start gap-2 text-sm text-gray-700'>
                <span className='w-1.5 h-1.5 rounded-full bg-yellow-500 mt-2 flex-shrink-0' />
                {item}
              </li>
            ))}
          </ul>
        </Card>
      )}

      {/* Recommendation */}
      <Card>
        <div className='flex items-center gap-2 mb-3'>
          <div className='w-7 h-7 bg-blue-50 rounded-lg flex items-center justify-center'>
            <svg className='w-4 h-4 text-blue-600' fill='none' viewBox='0 0 24 24' stroke='currentColor'>
              <path strokeLinecap='round' strokeLinejoin='round' strokeWidth={2} d='M9.663 17h4.673M12 3v1m6.364 1.636l-.707.707M21 12h-1M4 12H3m3.343-5.657l-.707-.707m2.828 9.9a5 5 0 117.072 0l-.548.547A3.374 3.374 0 0014 18.469V19a2 2 0 11-4 0v-.531c0-.895-.356-1.754-.988-2.386l-.548-.547z' />
            </svg>
          </div>
          <h3 className='text-sm font-semibold text-gray-900'>Recommendation</h3>
        </div>
        <p className='text-sm text-gray-700 leading-relaxed'>{report?.recommendation}</p>
      </Card>

    </div>
  )
}